// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type User struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}
